[versions]
agp = "8.9.0"
kotlin = "2.1.20"
lifecycle-runtime = "2.8.7"

[libraries]
core-ktx = "androidx.core:core-ktx:1.15.0"
junit = "junit:junit:4.13.2"
androidx-test-ext-junit = "androidx.test.ext:junit:1.2.1"
espresso-core = "androidx.test.espresso:espresso-core:3.6.1"
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle-runtime" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime" }
activity-compose = "androidx.activity:activity-compose:1.10.1"
compose-bom = "androidx.compose:compose-bom:2025.03.00"
ui = { module = "androidx.compose.ui:ui" }
ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
material3 = { module = "androidx.compose.material3:material3" }
datastore-preferences = "androidx.datastore:datastore-preferences:1.1.3"
maps = "com.google.maps.android:maps-compose:6.5.2"
accompanist-permissions = "com.google.accompanist:accompanist-permissions:0.37.2"
play-services-location = "com.google.android.gms:play-services-location:21.3.0"
work-runtime = "androidx.work:work-runtime-ktx:2.10.0"
splashscreen = "androidx.core:core-splashscreen:1.0.1"
core-google-shortcuts = "androidx.core:core-google-shortcuts:1.1.0"
androidx-uiautomator = "androidx.test.uiautomator:uiautomator:2.3.0"
androidx-benchmark-macro-junit4 = "androidx.benchmark:benchmark-macro-junit4:1.3.3"
androidx-profileinstaller = "androidx.profileinstaller:profileinstaller:1.4.1"

[plugins]
android-application = {id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
maps-secrets = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin:2.0.1"
android-test = { id = "com.android.test", version.ref = "agp" }
baselineprofile = "androidx.baselineprofile:1.3.3"
