name: Build

on: workflow_dispatch

jobs:
  build:
    name: Release Build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      actions: read
      contents: write
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | \
            sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Create Secrets
        id: secrets
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_PATH: ${{ secrets.KEYSTORE_PATH }}
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
        run: |
          echo storePassword=$KEYSTORE_PASSWORD >> ./release.properties
          echo keyPassword=$KEYSTORE_PASSWORD >> ./release.properties
          echo storeFile=$KEYSTORE_PATH >> ./release.properties
          echo MAPS_API_KEY=$MAPS_API_KEY >> ./release.properties
          echo $KEYSTORE_BASE64 | base64 --decode > app/$KEYSTORE_PATH

      - name: Build app and benchmark
        run: ./gradlew incrementVersionCode assembleNonMinifiedRelease

      - name: Clean Managed Devices
        run: ./gradlew cleanManagedDevices --unused-only

      - name: Generate Baseline Profile
        run: |
          ./gradlew :app:generateBaselineProfile \
            -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect" \
            -Pandroid.experimental.testOptions.managedDevices.setupTimeoutMinutes=20

      - name: Build Release
        run: ./gradlew :app:assembleRelease

      - name: Get Release info
        id: release_info
        run: echo "version=$(./gradlew fullVersion -q --console=plain)" >> $GITHUB_OUTPUT

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update for release'

      - name: Create Release
        run: |
          gh release create v$APP_VERSION --latest --generate-notes \
            app/build/outputs/apk/release/app-release.apk
        env:
          APP_VERSION: ${{ steps.release_info.outputs.version }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
