name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Release Build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      actions: read
      contents: write
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Enable KVM
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    - name: Set Up JDK
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 21

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Create release.properties
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEYSTORE_PATH: ${{ secrets.KEYSTORE_PATH }}
        MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
      run: |
        echo storePassword=$KEYSTORE_PASSWORD >> ./release.properties
        echo keyPassword=$KEYSTORE_PASSWORD >> ./release.properties
        echo storeFile=$KEYSTORE_PATH >> ./release.properties
        echo MAPS_API_KEY=$MAPS_API_KEY >> ./release.properties

    - name: Decode keystore
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        KEYSTORE_PATH: ${{ secrets.KEYSTORE_PATH }}
      run: |
        echo $KEYSTORE_BASE64 > keystore-b64.txt
        base64 -d keystore-b64.txt > app/$KEYSTORE_PATH

    - name: Build app and benchmark
      run: ./gradlew incrementVersionCode assembleNonMinifiedRelease

    - name: Clean Managed Devices
      run: ./gradlew cleanManagedDevices --unused-only

    - name: Generate Baseline Profile
      run: |
        ./gradlew :app:generateBaselineProfile \
          -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect" \
          -Pandroid.experimental.testOptions.managedDevices.setupTimeoutMinutes=20

    - name: Build Release
      run: ./gradlew :app:assembleRelease

    - name: Get build version
      id: get_build_version
      run: echo "version=$(./gradlew fullVersion -q --console=plain)" >> "$GITHUB_OUTPUT"

    - name: Cleanup
      if: always()
      env:
        KEYSTORE_PATH: ${{ secrets.KEYSTORE_PATH }}
      run: |
        rm release.properties
        rm keystore-b64.txt
        rm app/$KEYSTORE_PATH

    - name: Tag Release
      uses: EndBug/add-and-commit@v9
      with:
        message: 'Update for release'
        tag: 'v${{ steps.get_build_version.outputs.version }}'

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: app/build/outputs/apk/release/app-release.apk
        tag_name: 'v${{ steps.get_build_version.outputs.version }}'
