name: "CI"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      actions: read
      contents: write
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4

    - name: Validate gradle wrapper
      uses: gradle/wrapper-validation-action@699bb18358f12c5b78b37bb0111d3a0e2276e0e2 # v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@8a470fddafa5cbb6266ee11b37ef4d8aae19c571 # v3
      with:
        languages: "java-kotlin"
        queries: security-and-quality

    - name: Set Up JDK
      uses: actions/setup-java@9704b39bf258b59bc04b50fa2dd55e9ed76b47a8 # v4
      with:
        distribution: zulu
        java-version: 21

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3
      with:
        dependency-graph: generate-and-submit
        build-scan-publish: true
        build-scan-terms-of-service-url: "https://gradle.com/terms-of-service"
        build-scan-terms-of-service-agree: "yes"

    - name: Create secrets.properties
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
        KEYSTORE_PATH: ${{ secrets.KEYSTORE_PATH }}
        MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
      run: |
        echo storePassword=$KEYSTORE_PASSWORD >> ./secrets.properties
        echo keyPassword=$KEYSTORE_PASSWORD >> ./secrets.properties
        echo keyAlias=$KEYSTORE_ALIAS >> ./secrets.properties
        echo storeFile=$KEYSTORE_PATH >> ./secrets.properties
        echo MAPS_API_KEY=$MAPS_API_KEY >> ./secrets.properties

    - name: Decode keystore
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        KEYSTORE_PATH: ${{ secrets.KEYSTORE_PATH }}
      run: |
        echo $KEYSTORE_BASE64 > keystore-b64.txt
        base64 -d keystore-b64.txt > app/$KEYSTORE_PATH

    - name: Build
      run: ./gradlew build

    - name: Cleanup
      if: always()
      env:
        KEYSTORE_PATH: ${{ secrets.KEYSTORE_PATH }}
      run: |
        rm secrets.properties
        rm keystore-b64.txt
        rm app/$KEYSTORE_PATH

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@8a470fddafa5cbb6266ee11b37ef4d8aae19c571 # v3
      with:
        upload: false
        output: sarif-results

    - name: Filter SARIF
      uses: advanced-security/filter-sarif@f3b8118a9349d88f7b1c0c488476411145b6270d # v1
      with:
        patterns: |
          -.gradle/**
        input: sarif-results/java.sarif
        output: sarif-results/java.sarif

    - name: Upload SARIF
      uses: github/codeql-action/upload-sarif@8a470fddafa5cbb6266ee11b37ef4d8aae19c571 # v3
      with:
        sarif_file: sarif-results/java.sarif
        category: "/language:java-kotlin"

    - name: Upload lint results
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4
      with:
        name: lint-results
        path: app/build/reports/lint-results-debug.html

    - name: Upload Release APK
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4
      with:
        name: android-build-outputs
        path: app/build/outputs/apk/release/app-release.apk
